import { StyleSheet } from 'react-native';

const profileStyles = (colors) =>
  StyleSheet.create({
    scrollContainer: {
      flexGrow: 1,
      alignItems: 'center',
      paddingVertical: 20,
      backgroundColor: colors.background,
    },
    container: {
      width: '90%',
      backgroundColor: colors.cardBackground || '#fff',
      borderRadius: 20,
      paddingVertical: 20,
      paddingHorizontal: 15,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 5,
      marginBottom: 20,
    },
    profileImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: colors.imageBackground || '#e0e0e0',
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    headerText: {
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
      color: colors.text,
      marginBottom: 5,
    },
    profileName: {
      fontSize: 16,
      color: colors.textSecondary || '#777',
      textAlign: 'center',
      marginBottom: 15,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.text,
      alignSelf: 'flex-start',
      marginBottom: 5,
    },
    bioText: {
      fontSize: 14,
      color: colors.textSecondary || '#555',
      lineHeight: 20,
      marginBottom: 10,
      textAlign: 'left',
      width: '100%',
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      marginTop: 10,
      marginBottom: 20,
    },
    button: {
      backgroundColor: colors.buttonBackground || '#007bff',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      width: '45%',
    },
    buttonText: {
      color: colors.buttonText || '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    addImageButton: {
      marginTop: 20,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      alignItems: 'center',
      alignSelf: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      backgroundColor: colors.buttonBackground || '#007bff',
    },
    addImageButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.buttonText || '#fff',
    },
    noImagesText: {
      fontSize: 14,
      color: colors.textSecondary || '#777',
      textAlign: 'center',
      marginTop: 20,
    },
    imageGallery: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      marginTop: 10,
    },
    galleryImage: {
      width: 100,
      height: 100,
      borderRadius: 10,
      margin: 5,
      backgroundColor: colors.imageBackground || '#e0e0e0',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
    },
    galleryItem: {
      position: 'relative',
      margin: 5,
    },
    removeImageButton: {
      position: 'absolute',
      top: 5,
      right: 5,
      backgroundColor: 'rgba(255, 0, 0, 0.8)',
      borderRadius: 15,
      width: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    removeImageButtonText: {
      color: '#fff',
      fontWeight: 'bold',
    },
  });

export default profileStyles;
